global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:9101"]

  - job_name: master-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - master-backend-1:9190
          - master-backend-2:9190
          - master-backend-3:9190

  - job_name: db-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - db-backend-1:9191
          - db-backend-2:9191
          - db-backend-3:9191

  - job_name: ai-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - ai-backend-1:9192
          - ai-backend-2:9192
          - ai-backend-3:9192

  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ["envoy:9901"]
